### ISSUE TITLE
Missing sy/syinterfaces.h

### ISSUE THREAD

**Issue by paraenggu** [ElvishArtisan/drouter#1]
I'm trying to get `drouter` up and running for testing purposes, but fail to compile it on CentOS 7:
```bash
./configure --prefix=/opt/drouter
```
```
[...]
checking for SWITCHYARD... no
configure: error: *** Switchyard not found ***
```

After some browsing, I found a Switchyard library tarball within the [switchyard source RPM](http://caspian.paravelsystems.com/CentOS/7/CentOS/switchyard-0.13.3-1.el7.centos.src.rpm) (I'm not sure if this is the canonical upstream source). After the installation of the [`switchyard-devel`](http://caspian.paravelsystems.com/CentOS/7/CentOS/switchyard-devel-0.13.3-1.el7.centos.x86_64.rpm) package, `configure` succeeds, but make still fails:

```bash
DOCBOOK_STYLESHEETS=/usr/share/sgml/docbook/xsl-ns-stylesheets-1.78.1 make
```
```
[...]
Making all in dmap
make[2]: Entering directory `/home/builder/drouter/src/dmap'
  CXX      dmap.o
dmap.cpp:30:29: fatal error: sy/syinterfaces.h: No such file or directory
 #include <sy/syinterfaces.h>
```

After verifying that `syinterfaces.h` is really missing in `/usr/include/sy` and the `switchyard-0.13.3` tarball, I realized that there's already a [`drouter`](http://caspian.paravelsystems.com/CentOS/7/CentOS/drouter-0.6.1-1.el7.centos.x86_64.rpm) RPM available. However, `drouterd` from this package also seems to miss `SyInterfaces`:
```bash
LD_DEBUG=libs drouterd
```
```
[...]
      5127:	
      5127:	find library=libSwitchyard.so.3 [0]; searching
      5127:	 search cache=/etc/ld.so.cache
      5127:	  trying file=/lib64/libSwitchyard.so.3
[...]
      5127:	calling init: /lib64/libSwitchyard.so.3
[...]
      5127:	drouterd: error: symbol lookup error: undefined symbol: _ZN12SyInterfacesC1Ev (fatal)

drouterd: symbol lookup error: drouterd: undefined symbol: _ZN12SyInterfacesC1Ev
```

```bash
nm -D /lib64/libSwitchyard.so.3 | grep --count SyInterfaces
```
```
0
```

Any hints on where to find `sy/syinterfaces.h` would be highly appreciated. On the other hand,  I probably simply missed to install the correct dependency to use the `drouter` RPM.

Many thanks!

**Comment by ElvishArtisan** [comment]
That's an old version. You can get the current version (v0.11.1) at:
http://github.com/ElvishArtisan/Switchyard

**Comment by paraenggu** [comment]
Thanks a lot! How could I miss that repository in the first place :-( While browsing the release [tags](https://github.com/ElvishArtisan/Switchyard/tags) of `Switchyard` I wonder if _0.11.1_ is the correct release, shouldn't it be _0.17.1_?

**Comment by ElvishArtisan** [comment]
I had actually had it marked 'private'. That library has actually been open for some time now; this was a good reminder to open the repo and update all the licensing bits appropriately.

**Comment by paraenggu** [comment]
Thanks you so much, I'm now able to build `drouter` on CentOS 7.

Do you have any plans on bumping the `drouter` and `switchyard` RPMs located at [caspian.paravelsystems.com](http://caspian.paravelsystems.com/CentOS/7/CentOS/)? If you don't find the time, I could create builds on the [public OBS](https://build.opensuse.org/) in the meantime.

**Comment by ElvishArtisan** [comment]
On Feb 27, 2018, at 02:38, Christian Affolter <notifications@github.com> wrote:

> Do you have any plans on bumping the drouter and switchyard RPMs located at caspian.paravelsystems.com <http://caspian.paravelsystems.com/CentOS/7/CentOS/>? If you don't find the time, I could create builds on the public OBS <https://build.opensuse.org/> in the meantime.

Hi Christian:

Drouter is already at the current release (v0.6.1). I’ve just bumped switchyard to 0.17.1.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by paraenggu** [comment]
> Drouter is already at the current release (v0.6.1). I’ve just bumped switchyard to 0.17.1.

Nice, thanks a lot. `drouterd` from the [Paravel-Broadcast](http://download.paravelsystems.com/CentOS/7/) repository is now working again.
